### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Grelo** [07th-mod/meakashi#13]
@enumag There is a bug when the game freezes. Its at the end of **_meak_ep_02** file, when Shion stabs Keiichi. Maybe something is missing from the script. You can only quit game cause even the menu is fucked up afterwards.

![20170706110743_1](https://user-images.githubusercontent.com/22790067/27904209-34f09d92-623c-11e7-968e-f7ba22af8c73.jpg)

**Comment by enumag** [comment]
@Grelo Damn. This is what I was afraid of. Can I see your log file to confirm it is indeed the error I expect?

**Comment by Grelo** [comment]
I hope its the right file
[output_log.txt](https://github.com/07th-mod/meakashi/files/1128742/output_log.txt)

**Comment by enumag** [comment]
@Grelo It is. And the bug is exactly what I was afraid of.

The thing is that the game froze during my testing previously because the `AdvMode` variable suddenly did not exist after using a `CallScript` function. So I added [some code](https://github.com/07th-mod/meakashi/blob/adv-mode/Update/_meak_ep_02.txt#L787-L794) to redefine it which fixed the freeze for me.

For you it freezes because the variable already exists which means it behaves differently on my PC than it does on yours. I have no idea why.

Can you try reinstalling the base Meakashi game from MG to make sure you have the latest version, then reapply the patch, make sure that CompileUpdateScripts is empty and test it again? I'll do the same on my machine. Hopefully one of us has some old and buggy version of the game engine.

**Comment by Grelo** [comment]
@enumag Reinstalled, tried everything still freezes.

**Comment by enumag** [comment]
@Grelo Then I guess I had some old version. After reinstalling the game freezed for me too. I reverted that change. I hope to never see such issue again.
