### ISSUE TITLE
meakashi patch installer.exe flagged as virus/malware

### ISSUE THREAD

**Issue by ArmandBernard** [07th-mod/meakashi#16]
My antivirus, Bitdefender, blocked "meakashi patch installer.exe" when it ran, claiming it's a backdoor something or other.
The weird things is, I didn't even run the file, so that implies it ran itself to be detected. Have your files been infected or is this a false positive? This is a pretty old version of the installer, from June of last year.

**Comment by ItaloKnox** [comment]
Hey, hello. It's just a false positive. I recommend you to grab the newest installer, though, because if I recall correctly we changed a few things in the installation process and running an older installer will just not work correctly now. It's a 5mb file, so it shouldn't take long to download.

About the false positive, some antivirus software will flag the installer because it works in two steps:
1. the installer unpacks the dependencies needed to extract and install the patch in the game folder
2. the installer then autoruns a file that is inside the game folder to continue installation

Because the second step is made on Windows Command Prompt, some antivirus software will get wary. The only way the installer could be infected would be if:
* you downloaded it somewhere that isn't in our official organization on Github
* someone got write access to one of the collaborators' account

The second point could happen but we never had any issues with that in the past (the project has been going for a few years already) and we audit **all** the changes that happen in the repositories. Because of that, if anything suspicious happened we would have revoked the collaborator's right to write and reverted the changes before it could have done damage.

In case you don't want to risk yourself (even though you can see the actual code of the installer by going into our [resources](https://github.com/07th-mod/resources/) repository), I recommend you to use the manual installation process.

I hope that clarifies the issue! 😄
