### ISSUE TITLE
Audio files are from Himatsubushi, not Meakashi

### ISSUE THREAD

**Issue by odacaesar** [07th-mod/meakashi#17]
Earlier I downloaded these files, and noticed they were labeled "Himatsubushi-Voices.zip."  I thought this was merely a mislabeling, but a side-by-side comparison is showing me that these are actually the same audio recordings as "Himatsubushi-voices.zip."  Furthermore, the sound files are playing dialogue from _Himatsubushi-hen_, from characters such as Akasaka and Rika; and not _Meakashi-hen_ dialogue from characters like Shion, Mion, and Keiichi.

Does anybody have the actual _Meakashi-hen_ voices, and would somebody be willing to submit them in a new .zip to replace the "Himatsubushi-voices" duplicate?

**Comment by ItaloKnox** [comment]
Give me a minute to check this. Where did you get the links to download the files?

**Comment by odacaesar** [comment]
https://github.com/07th-mod/meakashi/releases/tag/v3.0.1

linked there from—
https://github.com/07th-mod/guide/wiki/Higurashi-Part-1---Voice-and-Graphics-Patch#installer-windows-only

**Comment by ItaloKnox** [comment]
I'm failing to understand what is the issue. Are you sure you aren't mistaken about the file?

Let me break it down for you:
Meakashi v3.0.1 contains indeed a ``voice`` folder. The voices in this folder are the voices for **Meakashi**, not Himatsubushi. The same applies to Himatsubushi v3.0.1, the ``voice`` folder that comes with the patch is actually the right one just like Meakashi, I compared them to the repository.

Now, about ``Himatsubushi-Voices.zip`` and ``Meakashi-Voices.zip``, both are different files. I diffed them and they don't have the same files. I can attach a very long log that makes the comparison, but it shouldn't be worth your time.

I also checked the installer code for Himatsubushi **and** Meakashi and didn't find any swapped calls for the games. They are all downloading files for the right chapter if you use the installer.

To end it, I extracted ``Himatsubushi-Voices.zip`` and then extracted ``Meakashi-Voices.zip``, and there was no prompt to overwrite a single file like expected. There are no duplicates or shared files between the chapters.

I will need more information to understand what is happening with you because I don't see any issues with our files.

**Comment by ItaloKnox** [comment]
In any case, this is the correct download link for the Meakashi voices: https://github.com/07th-mod/resources/releases/download/Nipah/Meakashi-Voices.zip

Follow the [tutorial](https://github.com/07th-mod/guide/wiki/Higurashi-Part-1---Voice-and-Graphics-Patch#manual-installation-windowslinuxmac) in case you have any questions.
