### ISSUE TITLE
Alternate Ending

### ISSUE THREAD

**Issue by orian34** [07th-mod/meakashi#41]
https://github.com/07th-mod/meakashi/blob/1e6c9e69631f1c7716b7bd9846cb492f8a063a74/Update/_meak_024.txt#L2542
link to where the choice is going to be in the script.
https://www.youtube.com/watch?v=jGnZU5mc9UE
The ending.

**Comment by DoctorDiablo** [comment]
@enumag Here are the script files for the Meakashi alternate ending.  This splits off from Mea at the point @orian34 identified.  I didn't commit them to the repo yet because I don't recall if we ever decided on adding this directly to Mea, or sticking it in the console arcs somewhere.

[meak_badend.txt](https://github.com/07th-mod/meakashi/files/3270119/meak_badend.txt)
[meak_badend_cont.txt](https://github.com/07th-mod/meakashi/files/3270120/meak_badend_cont.txt)

There's still some work to be done to get this fully implemented:
- [ ] Go through these script files and manually fix effects that couldn't be implemented automatically
- [ ] Translate all Japanese lines to English
- [ ] Identify any graphics and voice files needed for these scripts and package them with the release
- [ ] The scripts above currently use PS3 sound effects and music.  We can either change the script to use PC audio, or we can package those additional audio files with the release

**Comment by enumag** [comment]
I uploaded the translated scripts and ran than through the adv-mode + lipsync compiler. They are in this branch: https://github.com/07th-mod/meakashi/tree/feature/bad-end

**Comment by orian34** [comment]
I edited the scripts and now what's left is mostly to gather the resources needed.

**Comment by enumag** [comment]
All done.
