### ISSUE TITLE
Weird Tips Changes

### ISSUE THREAD

**Issue by tellowkrinkle** [07th-mod/meakashi#43]
In the switch from hardcoded tips to tips loaded from a JSON file, a few of the tips got changed.
- Tip 1 JP went from `考察メモ冒頭` to `ノートの冒頭`, I assume this was a PC → Console difference, do we want to keep it?
- Tip 22 EN went from `A Happy Diary` to `A Happy Note` (Japanese: `幸せのノート`)
I don't think `Note` fits this usage (it's referring to the notebook that held all the pages in previous tips), but would be fine with either `Diary` or `Notebook`.
  - Other things to think about when deciding this: The text content of the tip uses [`幸せな日記`](https://github.com/07th-mod/meakashi/blob/93c7e63ad5032ba931dfe5236b4c403753f63fe0/Update/_meak_tips_22.txt#L194), which gets translated as `happy diary`.  I was thinking we might want to try to keep this distinction but the text also later uses a [`日記`](https://github.com/07th-mod/meakashi/blob/93c7e63ad5032ba931dfe5236b4c403753f63fe0/Update/_meak_tips_22.txt#L211) that gets translated as `notebook`...

**Comment by InochiPM** [comment]
I saw something about this before, "ノート" can refer to a multitude of things that have the word "Note" in them, It can mean a notebook, a note (like taking notes), musical notes ect. So it's used very loosely when they picked the names i think? 

Most of the time when i saw the word "Note" being used in the mangagamer TL it was in place of "メモ/Memo" randomly, which kinda makes sense but a memo implies its a shortly written message. Most people use the word memo to signify something short they want to remember, so i can see why it was changed in japanese to a note/message. In that particular tips does it refer to anything like a notebook being read? 

It would be strange to think they would use Note in the place of Diary since their two different words  entirely.

**Comment by tellowkrinkle** [comment]
The original MG translation uses `Diary`
The new JSON (whose source is unknown to me) uses `Note`
This is the second to last tip with Ooishi reviewing the notebook we had been getting clips of in previous tips.

**Comment by ItaloKnox** [comment]
Really late to the party but I believe that using ``note`` in english is not *really* correct in this context. The word in english isn't as generic as in japanese, so I believe it should be changed according to the context. If it says ``A Happy Note``, it should mean that it is a single page or small note/memo. However, if the context makes it seem like a diary (in a private sense) or a notebook (like a school one), the ``Note`` part should be changed in english since it is not exactly the same thing as in japanese. Lastly, using ``note`` instead of ``memo`` works in english, but not so much in japanese.

I suggest just going over it and making a choice whether or not to change it. There's no need to think too deeply about it.

**Comment by tellowkrinkle** [comment]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/3315070/57184678-9b321580-6e84-11e9-9789-35527a234df9.png">

I checked matsuribayashi disk and it also uses `ノートの冒頭`.
