### ISSUE TITLE
The newest GOG version of UI boots with black screen

### ISSUE THREAD

**Issue by sdd264** [07th-mod/meakashi#76]
The newest version of GOG Meakashi doesn't boot with the newest version (5.5.3p3), at least when installed manually, whereas 5.5.3p1 works without a problem

**Comment by ItaloKnox** [comment]
That is a known issue for a while already. I don't remember the details, but when that happens, the user should get the ``GOG (old)†`` package instead. We already had cases where we had to swap the links around and this issue always comes back at some point. For now, we're leaving it like that since we can't track down the source of the GOG builds a lot of our users get (since it's not uncommon to see pirated GOG downloads around).

**Comment by sdd264** [comment]
I see. Thank you for clarification and good luck

**Comment by ItaloKnox** [comment]
No problem, thanks!
